# Generated by Django 2.2 on 2021-05-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210528_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='rating',
        ),
    ]
