# Generated by Django 2.2 on 2021-05-28 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_quote_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rating'),
        ),
    ]
